FROM node:22-alpine

WORKDIR /app

RUN apk add --no-cache libc6-compat

# Copy toàn bộ mã nguồn frontend vào container
COPY frontend/web /app

# Cài đặt dependencies (bao gồm dev)
RUN npm install

EXPOSE 3000

ENV NODE_ENV=development

CMD ["npm", "run", "dev"]
