// app/layout.tsx
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import { SessionProvider } from "next-auth/react";
import { getCurrentUser } from "./actions/authactions";
import SignalRProvider from "./Providers/SignalRProvider";
import { Toaster } from "react-hot-toast";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});
const user = await getCurrentUser();
const notifyUrl = process.env.NOTIFY_URL;


const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <SessionProvider>
          <SignalRProvider notifyUrl={notifyUrl!} user={user}>
            <Navbar />
            {children}
            <Footer />
            <Toaster position="top-right" />
          </SignalRProvider>
        </SessionProvider>

      </body>
    </html>
  );
}
