// <auto-generated />
using System;
using AuctionService.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AuctionService.Data.Migrations
{
    [DbContext(typeof(AuctionDbContext))]
    partial class AuctionDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AuctionService.Entites.Auction", b =>
                {
                    b.Property<string>("ID")
                        .HasColumnType("text");

                    b.Property<int>("bidStep")
                        .HasColumnType("integer");

                    b.Property<int>("currentPrice")
                        .HasColumnType("integer");

                    b.Property<DateTime>("endTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("productID")
                        .HasColumnType("text");

                    b.Property<string>("sellerID")
                        .HasColumnType("text");

                    b.Property<int>("startPrice")
                        .HasColumnType("integer");

                    b.Property<DateTime>("startTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("winnerID")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ID");

                    b.ToTable("Auctions");
                });

            modelBuilder.Entity("AuctionService.Entites.Bid", b =>
                {
                    b.Property<string>("ID")
                        .HasColumnType("text");

                    b.Property<string>("auctionID")
                        .HasColumnType("text");

                    b.Property<int>("bidAmount")
                        .HasColumnType("integer");

                    b.Property<DateTime>("bidTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("userID")
                        .HasColumnType("text");

                    b.HasKey("ID");

                    b.HasIndex("auctionID");

                    b.ToTable("Bids");
                });

            modelBuilder.Entity("AuctionService.Entites.Bid", b =>
                {
                    b.HasOne("AuctionService.Entites.Auction", "auction")
                        .WithMany()
                        .HasForeignKey("auctionID");

                    b.Navigation("auction");
                });
#pragma warning restore 612, 618
        }
    }
}
